### ISSUE TITLE
Table function does not handle inputs with commas

### ISSUE THREAD

**Issue by evelynccordner** [oclif/cli-ux#105]
The `table` function does not properly handle inputs with commas when `csv = true`.

Example: 
```
    cli.table(
      [
        {index: 1, text: 'test'},
        {index: 2, text: 'test, test'},
        {index: 3, text: 'test, test, test'},
      ],
      {
        index: {header: 'Index'},
        text: {header: 'Text'},
      },
      {csv: true},
    );
```

Expected Output:
![Screen Shot 2019-06-06 at 11 34 25 AM](https://user-images.githubusercontent.com/5140736/59057406-28cf9f00-884f-11e9-9753-0093ae9c040f.png)

Received Output:
![Screen Shot 2019-06-06 at 11 33 35 AM](https://user-images.githubusercontent.com/5140736/59057426-3127da00-884f-11e9-9f98-74c4a8064bed.png)

**Comment by RasPhilCo** [comment]
Ooh no good!
