### ISSUE TITLE
xdg-open does not work on ubuntu linux

### ISSUE THREAD

**Issue by ransombriggs** [oclif/cli-ux#114]
I am trying to use `open` on ubuntu linux but run into issues here because it is trying to use an `xdg-open` which does not [appear to exist](https://github.com/oclif/cli-ux/blob/master/src/open.ts#L56)

```
await cli.open('https://example.com')
```

```
-> % ./bin/run
Error: spawn /home/rbriggs/src/github.com/example/example/node_modules/cli-ux/lib/xdg-open ENOENT
```

**Comment by rhwood** [comment]
`xdg-open` is part of the (`xdg-utils` package)[https://packages.ubuntu.com/search?suite=bionic&arch=any&mode=exactfilename&searchon=contents&keywords=xdg-open] in Ubuntu. Is it not installed by default anymore?

**Comment by ransombriggs** [comment]
@rhwood it does, the CLI was just trying to point to an absolute path that does not exist, I went to find the bug and it turns out that @RasPhilCo already fixed this in https://github.com/oclif/cli-ux/pull/133
