### ISSUE TITLE
Spinner examples are incorrect

### ISSUE THREAD

**Issue by robcresswell** [oclif/cli-ux#123]
The examples for the spinner do not match the types. In the root `README.md`, there is the following example:

```
cli.action.start('starting a process', {stdout: true})
```

The second parameter is supposedly `status`, which is a `string`. It doesn't seem to be documented.

**Comment by spaghetti-is-pasta** [comment]
Correct, the README should state:

`cli.action.start('starting a process', null, {stdout: true})`

**Comment by RasPhilCo** [comment]
Thanks! Fixed in https://github.com/oclif/cli-ux/commit/854416bdc8afdf8f63e0a549d9f830fb85037bee.

**Comment by robcresswell** [comment]
Thanks @RasPhilCo
