### ISSUE TITLE
cli.table unable to have both --csv and --no-header flags.

### ISSUE THREAD

**Issue by tlee32** [oclif/cli-ux#240]
OS: MacOS
cli-ux: 5.5.0
node: v13.11.0

I get the following error when I try to pass in both --csv and --no-header flags to a command that uses cli.table:
```
./bin/run --no-header --csv
 ›   Error: --csv= cannot also be provided when using --no-header=
```
Note: `./bin/run --output=csv --no-header` works.

### Steps to Reproduce
Copy / Paste the script below as a command:
```
const {Command, flags} = require('@oclif/command')
const { cli } = require('cli-ux')

class TestCommand extends Command {
  async run() {
    cli.table([{version:'1.0.0'}], {version:{}}, flags)
  }
}

TestCommand.description = `Describe the command here
...
Extra documentation goes here
`

TestCommand.flags = {
  // add flags from cli.table
  ...cli.table.flags()
}

module.exports = TestCommand
```
Run: `./bin/run --no-header --csv`

### Related PR
https://github.com/oclif/cli-ux/pull/124
It seems like we just need to take out 'csv' from this [line](https://github.com/ArchangelX360/cli-ux/blob/d75af81b282b7a900753c5f3aa468d5daeb0834e/src/styled/table.ts#L247)?

**Comment by RasPhilCo** [comment]
Closed via #124
