### ISSUE TITLE
Is there anyone maintaining this? (A lot of PRs waiting)

### ISSUE THREAD

**Issue by srlowe** [oclif/cli-ux#464]
I would like to contribute by trying to solve some of the bugs, but I'm put off by the number of PRs that have not been reviewed/merged.

There are currently 15 open PRs dating from almost 2 years ago (Feb 2020).  None of these appear to be waiting on CLA signatures.

Could anyone please comment on the state of this project?

Thanks

**Comment by RodEsp** [comment]
Yes, there is, sometimes it takes a while to get to certain things though.
