### ISSUE TITLE
Empty column header doesn't work

### ISSUE THREAD

**Issue by samuela** [oclif/cli-ux#72]
Attempting to silence a column header:
```typescript
cli.table(tableData, {
  name: {
    header: "",
  },
  ...
});
```
doesn't have any effect. The column header is still printed as "Name".

**Comment by RasPhilCo** [comment]
In javascript, `""` is falsey. You can use `" "`. But I'll update it to check for a string.

**Comment by samuela** [comment]
@RasPhilCo Yes, that's what I figured was going on so I switched to `" "`.
