### ISSUE TITLE
Password prompt is always required

### ISSUE THREAD

**Issue by mhverbakel** [oclif/cli-ux#73]
Similar to #26, the `required` option is ignored if the type is set to `hide` or `mask` (since the underlying library does not support it). Same holds for the `default` option.

**Comment by elbandito** [comment]
Hi @mhverbakel,

I want to make I'm understanding you correctly. 

Doing the following will allow the user to hit enter without any input:
`const input = await cli.prompt('This is a prompt', {type: 'hide', required: false})`

Doing the following will require the user to input text before they hit enter:
`const value = await cli.prompt('This is a prompt', {type: 'hide', required: true})`
**OR**
`const value = await cli.prompt('This is a prompt', {type: 'hide')`

Are these ^ the requirements you're asking for?

**Comment by mhverbakel** [comment]
Those are correct, but incomplete.
1. Allow the user to hit enter without any input:
`const input = await cli.prompt('Enter a password, or not', { type: 'hide', required: false })`
yielding `input = ''` when enter is hit immediately.
2. Allow the user to hit enter without any input, taking the default instead.
`const input = await cli.prompt('Enter a password, or not', { type: 'hide', default: 'hide me' })`
yielding `input = 'hide me'` when enter is hit immediately, hiding the default value.
3. Require the user to input text before hitting enter (already working).
`const input = await cli.prompt('Enter a password, definitely', { type: 'hide', required: true })`
or leaving out `required` at all.

Thanks for looking into this!

**Comment by elbandito** [comment]
@mhverbakel update to v5.2.0.
https://github.com/oclif/cli-ux/releases/tag/v5.2.0

**Comment by mhverbakel** [comment]
@elbandito Almost right.

I've made two pull requests to resolve the issues I'm still experiencing:
* https://github.com/jdxcode/password-prompt/pull/9
* https://github.com/oclif/cli-ux/pull/75 (and updating `password-prompt` ofcourse)

**Comment by elbandito** [comment]
@mhverbakel oh, so close.  We'll, reviewer your PRs - thanks!

**Comment by moulikcipherX** [comment]
This issue is still opened? @elbandito
