### ISSUE TITLE
Better prompting types

### ISSUE THREAD

**Issue by joshstrange** [oclif/cli-ux#90]
yeoman-generator (which is what is used to generate a new oclif CLI) has a number of more useful prompts like checkboxes/select which would be very useful. I, wrongly, assumed these types of prompts were available to me to use since they were used to create my CLI.

**Comment by jdxcode** [comment]
As mentioned [in the docs](https://oclif.io/docs/prompting). Use [inquirer](https://www.npmjs.com/package/inquirer).

**Comment by joshstrange** [comment]
Thank you, I somehow missed that but funnily enough found inquirer on my own and was moving forward with that.
